---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks: 
  - name: Ensure ssh port open
    ansible.builtin.wait_for:
      port: 22
      delay: 60
      timeout: 300
      search_regex: OpenSSH
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    vars:
      ansible_connection: local

- name: Update Installation
  hosts: all
  become: True
  become_user: root
  tasks:
  - name: Update apt repo and cache
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: "Install essential apps"
    ansible.builtin.apt: "name={{ item }} state=present"
    with_items:
      - net-tools
      - vim-scripts
  - name: Clean /etc/resolv.conf
    ansible.builtin.shell: |
      >/etc/resolv.conf
  - name: Apply dns config
    ansible.builtin.blockinfile:
      path: /etc/resolv.conf
      block: |
        nameserver 192.168.1.250
  - name: Copy key
    ansible.builtin.copy:
      src: /home/erasmus/.data/terraform/infra/bastion/pki/k8sdeployr
      dest: /home/k8sdeployr/.ssh/id_rsa
      owner: k8sdeployr
      group: k8sdeployr
      mode: '0600'
  - name: Add to ssh-agent
    ansible.builtin.shell: |
      eval "$(ssh-agent -s)"
      ssh-add /home/k8sdeployr/.ssh/id_rsa
    become: yes
    become_user: k8sdeployr
  - name: Stop and Start ssh
    ansible.builtin.service:
      name: ssh
      state: restarted

